Blog/Models/Imagemap.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Blog.Models
{
    public class Imagemap
    {
        [Key]
        public int Imagemap_Id { get; set; }
        [ForeignKey("Images")]
        public Nullable<int> Img_Id { get; set; }
        [ForeignKey("Articles")]
        public Nullable<int> Art_Id { get; set; }
        
        public virtual Images Images { get; set; }
        public virtual Articles Articles { get; set; }
    }
}

Blog/Controllers/ImagemapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.App_Start;
using Blog.Models;

namespace Blog.Controllers
{
    [Authorize]
    public class ImagemapsController : Controller
    {
        private BlogContext db = new BlogContext();

        // GET: Imagemaps
        public ActionResult Index()
        {
            var imagemap = db.Imagemap.Include(i => i.Articles).Include(i => i.Images);
            return View(imagemap.ToList());
        }

        // GET: Imagemaps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Imagemap imagemap = db.Imagemap.Find(id);
            if (imagemap == null)
            {
                return HttpNotFound();
            }
            return View(imagemap);
        }

        // GET: Imagemaps/Create
        public ActionResult Create()
        {
            ViewBag.Art_Id = new SelectList(db.Articles, "Art_Id", "Title");
            ViewBag.Img_Id = new SelectList(db.Images, "Img_Id", "Image");
            return View();
        }

        // POST: Imagemaps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Imagemap_Id,Img_Id,Art_Id")] Imagemap imagemap)
        {
            if (ModelState.IsValid)
            {
                db.Imagemap.Add(imagemap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Art_Id = new SelectList(db.Articles, "Art_Id", "Title", imagemap.Art_Id);
            ViewBag.Img_Id = new SelectList(db.Images, "Img_Id", "Image", imagemap.Img_Id);
            return View(imagemap);
        }

        // GET: Imagemaps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Imagemap imagemap = db.Imagemap.Find(id);
            if (imagemap == null)
            {
                return HttpNotFound();
            }
            ViewBag.Art_Id = new SelectList(db.Articles, "Art_Id", "Title", imagemap.Art_Id);
            ViewBag.Img_Id = new SelectList(db.Images, "Img_Id", "Image", imagemap.Img_Id);
            return View(imagemap);
        }

        // POST: Imagemaps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Imagemap_Id,Img_Id,Art_Id")] Imagemap imagemap)
        {
            if (ModelState.IsValid)
            {
                db.Entry(imagemap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Art_Id = new SelectList(db.Articles, "Art_Id", "Title", imagemap.Art_Id);
            ViewBag.Img_Id = new SelectList(db.Images, "Img_Id", "Image", imagemap.Img_Id);
            return View(imagemap);
        }

        // GET: Imagemaps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Imagemap imagemap = db.Imagemap.Find(id);
            if (imagemap == null)
            {
                return HttpNotFound();
            }
            return View(imagemap);
        }

        // POST: Imagemaps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Imagemap imagemap = db.Imagemap.Find(id);
            db.Imagemap.Remove(imagemap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blog/Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.App_Start;
using Blog.Models;

namespace Blog.Controllers
{
    [Authorize]
    public class ShopsController : Controller
    {
        private BlogContext db = new BlogContext();

        // GET: Shops
        public ActionResult Index()
        {
            return View(db.Shop.ToList());
        }

        // GET: Shops/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shop shop = db.Shop.Find(id);
            if (shop == null)
            {
                return HttpNotFound();
            }
            return View(shop);
        }

        // GET: Shops/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Shop_Id,Title,Link,Description,Information,Price,Stock,Image1,imageFile, Image2, imageFile2")]HttpPostedFileBase imageFile, HttpPostedFileBase imageFile2, Shop shop)
        {
            if (shop.Image1 == null)
            {
                shop.Image1 = "default.png";
            }
            if (shop.Image2 == null)
            {
                shop.Image2 = "default.png";
            }
            if (ModelState.IsValid)
            {
                string imageName1 = Path.GetFileNameWithoutExtension(shop.imageFile.FileName);
                string extension1 = Path.GetExtension(shop.imageFile.FileName);
                imageName1 += extension1;
                shop.Image1 = imageName1;
                imageName1 = Path.Combine(Server.MapPath("~/Content/images/"), imageName1);
                shop.imageFile.SaveAs(imageName1);

                string imageName2 = Path.GetFileNameWithoutExtension(shop.imageFile2.FileName);
                string extension2 = Path.GetExtension(shop.imageFile2.FileName);
                imageName2 += extension2;
                shop.Image2 = imageName2;
                imageName2 = Path.Combine(Server.MapPath("~/Content/images/"), imageName2);
                shop.imageFile2.SaveAs(imageName2);
                db.Shop.Add(shop);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(shop);
        }

        // GET: Shops/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shop shop = db.Shop.Find(id);
            if (shop == null)
            {
                return HttpNotFound();
            }
            return View(shop);
        }

        // POST: Shops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Shop_Id,Title,Link,Description,Information,Price,Stock,Image1,imageFile, Image2, imageFile2")]HttpPostedFileBase imageFile, HttpPostedFileBase imageFile2, Shop shop)
        {
            if (shop.Image1 == null)
            {
                shop.Image1 = "default.png";
            }
            if (shop.Image2 == null)
            {
                shop.Image2 = "default.png";
            }
            if (ModelState.IsValid)
            {
                string imageName1 = Path.GetFileNameWithoutExtension(shop.imageFile.FileName);
                string extension1 = Path.GetExtension(shop.imageFile.FileName);
                imageName1 += extension1;
                shop.Image1 = imageName1;
                imageName1 = Path.Combine(Server.MapPath("~/Content/images/"), imageName1);
                shop.imageFile.SaveAs(imageName1);

                string imageName2 = Path.GetFileNameWithoutExtension(shop.imageFile2.FileName);
                string extension2 = Path.GetExtension(shop.imageFile2.FileName);
                imageName2 += extension2;
                shop.Image2 = imageName2;
                imageName2 = Path.Combine(Server.MapPath("~/Content/images/"), imageName2);
                shop.imageFile2.SaveAs(imageName2);
                db.Entry(shop).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(shop);
        }

        // GET: Shops/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shop shop = db.Shop.Find(id);
            if (shop == null)
            {
                return HttpNotFound();
            }
            return View(shop);
        }

        // POST: Shops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Shop shop = db.Shop.Find(id);
            db.Shop.Remove(shop);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blog/Views/Imagemaps/Create.cshtml
@model Blog.Models.Imagemap

@{
    ViewBag.Title = "Create";
    ViewBag.Robot = "noindex, nofollow";
    ViewBag.Google = "noindex, nofollow";
    ViewBag.Bing = "noindex, nofollow";
    ViewBag.Url = "";
}
<ul class="nav nav-tabs">
    <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
    <li>@Html.ActionLink("Subcategories", "Index", "Subcategories")</li>
    <li>@Html.ActionLink("Articles", "Index", "Articles")</li>
    <li>@Html.ActionLink("Images", "Index", "Images")</li>
    <li class="active">@Html.ActionLink("Imagemap", "Index", "Imagemaps")</li>
    <li>@Html.ActionLink("Tags", "Index", "Tags")</li>
    <li>@Html.ActionLink("Tagmap", "Index", "Tagmaps")</li>
    <li>@Html.ActionLink("Comments", "Index", "Comments")</li>
    <li>@Html.ActionLink("Replies", "Index", "Replies")</li>
    <li>@Html.ActionLink("Shop", "Index", "Shops")</li>
</ul><br /><br />
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Imagemap</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Img_Id, "Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Img_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Img_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Art_Id, "Article", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Art_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Art_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Blog/Views/Imagemaps/Delete.cshtml
@model Blog.Models.Imagemap

@{
    ViewBag.Title = "Delete";
    ViewBag.Robot = "noindex, nofollow";
    ViewBag.Google = "noindex, nofollow";
    ViewBag.Bing = "noindex, nofollow";
    ViewBag.Url = "";
}
<ul class="nav nav-tabs">
    <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
    <li>@Html.ActionLink("Subcategories", "Index", "Subcategories")</li>
    <li>@Html.ActionLink("Articles", "Index", "Articles")</li>
    <li>@Html.ActionLink("Images", "Index", "Images")</li>
    <li class="active">@Html.ActionLink("Imagemap", "Index", "Imagemaps")</li>
    <li>@Html.ActionLink("Tags", "Index", "Tags")</li>
    <li>@Html.ActionLink("Tagmap", "Index", "Tagmaps")</li>
    <li>@Html.ActionLink("Comments", "Index", "Comments")</li>
    <li>@Html.ActionLink("Replies", "Index", "Replies")</li>
    <li>@Html.ActionLink("Shop", "Index", "Shops")</li>
</ul><br /><br />
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Imagemap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Articles.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Articles.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images.Image)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Blog/Views/Imagemaps/Details.cshtml
@model Blog.Models.Imagemap

@{
    ViewBag.Title = "Details";
    ViewBag.Robot = "noindex, nofollow";
    ViewBag.Google = "noindex, nofollow";
    ViewBag.Bing = "noindex, nofollow";
    ViewBag.Url = "";
}
<ul class="nav nav-tabs">
    <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
    <li>@Html.ActionLink("Subcategories", "Index", "Subcategories")</li>
    <li>@Html.ActionLink("Articles", "Index", "Articles")</li>
    <li>@Html.ActionLink("Images", "Index", "Images")</li>
    <li class="active">@Html.ActionLink("Imagemap", "Index", "Imagemaps")</li>
    <li>@Html.ActionLink("Tags", "Index", "Tags")</li>
    <li>@Html.ActionLink("Tagmap", "Index", "Tagmaps")</li>
    <li>@Html.ActionLink("Comments", "Index", "Comments")</li>
    <li>@Html.ActionLink("Replies", "Index", "Replies")</li>
    <li>@Html.ActionLink("Shop", "Index", "Shops")</li>
</ul><br /><br />
<h2>Details</h2>

<div>
    <h4>Imagemap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Articles.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Articles.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images.Image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Imagemap_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Blog/Views/Imagemaps/Edit.cshtml
@model Blog.Models.Imagemap

@{
    ViewBag.Title = "Edit";
    ViewBag.Robot = "noindex, nofollow";
    ViewBag.Google = "noindex, nofollow";
    ViewBag.Bing = "noindex, nofollow";
    ViewBag.Url = "";
}
<ul class="nav nav-tabs">
    <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
    <li>@Html.ActionLink("Subcategories", "Index", "Subcategories")</li>
    <li>@Html.ActionLink("Articles", "Index", "Articles")</li>
    <li>@Html.ActionLink("Images", "Index", "Images")</li>
    <li class="active">@Html.ActionLink("Imagemap", "Index", "Imagemaps")</li>
    <li>@Html.ActionLink("Tags", "Index", "Tags")</li>
    <li>@Html.ActionLink("Tagmap", "Index", "Tagmaps")</li>
    <li>@Html.ActionLink("Comments", "Index", "Comments")</li>
    <li>@Html.ActionLink("Replies", "Index", "Replies")</li>
    <li>@Html.ActionLink("Shop", "Index", "Shops")</li>
</ul><br /><br />
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Imagemap</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Imagemap_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Img_Id, "Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Img_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Img_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Art_Id, "Article", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Art_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Art_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Blog/Views/Imagemaps/Index.cshtml
@model IEnumerable<Blog.Models.Imagemap>

@{
    ViewBag.Title = "Index";
    ViewBag.Robot = "noindex, nofollow";
    ViewBag.Google = "noindex, nofollow";
    ViewBag.Bing = "noindex, nofollow";
    ViewBag.Url = "";
}
<ul class="nav nav-tabs">
    <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
    <li>@Html.ActionLink("Subcategories", "Index", "Subcategories")</li>
    <li>@Html.ActionLink("Articles", "Index", "Articles")</li>
    <li>@Html.ActionLink("Images", "Index", "Images")</li>
    <li class="active">@Html.ActionLink("Imagemap", "Index", "Imagemaps")</li>
    <li>@Html.ActionLink("Tags", "Index", "Tags")</li>
    <li>@Html.ActionLink("Tagmap", "Index", "Tagmaps")</li>
    <li>@Html.ActionLink("Comments", "Index", "Comments")</li>
    <li>@Html.ActionLink("Replies", "Index", "Replies")</li>
    <li>@Html.ActionLink("Shop", "Index", "Shops")</li>
</ul><br /><br />
<h2>Image Map</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Articles.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Images.Image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Articles.Title)
            </td>
            <td>
                <img src="~/Content/Images/@Html.DisplayFor(modelItem => item.Images.Image)" width="150" />
                
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Imagemap_Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Imagemap_Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Imagemap_Id })
            </td>
        </tr>
    }

</table>